### ISSUE TITLE
Задача 4.3

### ISSUE THREAD

**Issue by avasyukov** [arsen-davtyan/Exercise-1#2]
Найдите и устраните потенциальный segmentation fault в своём решении.

Прокомментируйте, зачем это нужно в решении:
https://github.com/arsen-davtyan/Exercise-1/blob/fe800da40d439dc275022793c0e814c810f0770b/4.3.c#L23-L24

**Comment by arsen-davtyan** [comment]
В начале цикла i мы предпологаем, что наиближайшая точка к cx,cy это x[i],y[i] (x[1],y[1]). при помощи цикла j мы либо убеждаемся что нету точек среди n-i ближе к cx,cy, либо наоборот находим эту точку и переносим параметры этой точки в начало массивов(меняя с предыдущими параметрами i-го элемента). Таким образом мы упорядочиваем массив так чтобы получить траекторию движения.
